# Generated by Django 4.2 on 2025-07-31 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departman')),
                ('is_technician', models.BooleanField(default=False, verbose_name='Teknisyen')),
                ('can_manage_stock', models.BooleanField(default=False, verbose_name='Stok Yönetimi')),
                ('can_manage_customers', models.BooleanField(default=False, verbose_name='Müşteri Yönetimi')),
                ('can_manage_services', models.BooleanField(default=False, verbose_name='Servis Yönetimi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
