# Generated by Django 4.2 on 2025-07-31 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VespaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('engine_size', models.CharField(max_length=50, verbose_name='Motor Hacmi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('image_url', models.URLField(blank=True, verbose_name='Resim URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Vespa Modeli',
                'verbose_name_plural': 'Vespa Modelleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20, unique=True, verbose_name='Müşteri ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(verbose_name='Adres')),
                ('plate_number', models.CharField(blank=True, max_length=20, verbose_name='Plaka')),
                ('registration_date', models.DateField(verbose_name='Kayıt Tarihi')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Harcama')),
                ('services_count', models.IntegerField(default=0, verbose_name='Servis Sayısı')),
                ('last_service', models.DateField(blank=True, null=True, verbose_name='Son Servis')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif'), ('vip', 'VIP')], default='active', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('vespa_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.vespamodel', verbose_name='Vespa Modeli')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part', verbose_name='Parça')),
                ('vespa_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.vespamodel', verbose_name='Vespa Modeli')),
            ],
            options={
                'verbose_name': 'Model Parçası',
                'verbose_name_plural': 'Model Parçaları',
                'unique_together': {('vespa_model', 'part')},
            },
        ),
    ]
