# Generated by Django 4.2 on 2025-07-31 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hareket Türü')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Hareket Türü',
                'verbose_name_plural': 'Hareket Türleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50, unique=True, verbose_name='Parça ID')),
                ('name', models.CharField(max_length=200, verbose_name='Parça Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Mevcut Stok')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Minimum Stok')),
                ('max_stock', models.IntegerField(default=0, verbose_name='Maksimum Stok')),
                ('url', models.URLField(blank=True, verbose_name='Ürün URL')),
                ('main_image', models.URLField(blank=True, verbose_name='Ana Resim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Parça',
                'verbose_name_plural': 'Parçalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Parça Kategorisi',
                'verbose_name_plural': 'Parça Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tedarikçi Adı')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='İletişim Kişisi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miktar')),
                ('previous_stock', models.IntegerField(verbose_name='Önceki Stok')),
                ('new_stock', models.IntegerField(verbose_name='Yeni Stok')),
                ('reason', models.CharField(max_length=200, verbose_name='Sebep')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referans')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.movementtype', verbose_name='Hareket Türü')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part', verbose_name='Parça')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.partcategory', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='Tedarikçi'),
        ),
    ]
